"""Deterministic fake AIProvider for tests (Standards §15).

Returns canned, valid output derived from the input so the test suite never
calls the real model — no cost, no network, no flakiness. Same input always
yields the same output.
"""

from __future__ import annotations

import hashlib

from app.models.enums import Triage

from .types import FailureEvidence, Subgraph, TriageLabel
from .usage import PHASE_GENERATION, PHASE_TRIAGE, CliUsage, record_usage

# The stub never invokes a real model, so there is no billed cost and no real token
# usage — it records a flagged-unavailable entry so the capture seam still fires
# under the stub (the aggregate counts the call; cost/tokens stay null). ADR-0049.
_STUB_USAGE = CliUsage.unavailable(model="stub")

# Deterministic keyword heuristic so the stub returns a believable, stable label
# (no real model): the hermetic suite exercises the whole triage WIRING without a
# network call. Order matters — the first matching bucket wins.
_TRIAGE_KEYWORDS: tuple[tuple[Triage, tuple[str, ...]], ...] = (
    (Triage.INFRA, ("timeout", "timed out", "connection", "refused", "unreachable")),
    (Triage.BAD_TEST, ("factory", "seed", "setup", "fixture", "no such table")),
    (Triage.FLAKY, ("flaky", "intermittent", "retry", "race")),
    (Triage.REAL_BUG, ("assert", "expected", "status", "unexpected", "mismatch")),
)


def stub_triage(failure: FailureEvidence) -> Triage:
    """A deterministic label from the evidence — the fake model's classifier."""
    record_usage(_STUB_USAGE, phase=PHASE_TRIAGE)
    haystack = f"{failure.outcome} {failure.message}".lower()
    for label, keywords in _TRIAGE_KEYWORDS:
        if any(keyword in haystack for keyword in keywords):
            return label
    return Triage.UNKNOWN


class StubAIProvider:
    def generate(self, prompt: str, context: Subgraph, budget_tokens: int) -> str:
        record_usage(_STUB_USAGE, phase=PHASE_GENERATION)
        fingerprint = hashlib.sha256(
            f"{prompt}\x00{context.render()}".encode()
        ).hexdigest()[:12]
        return (
            "// stub-generated by StubAIProvider\n"
            f"// fingerprint: {fingerprint}\n"
            f"// budget_tokens: {budget_tokens}\n"
        )

    def triage(self, failure: FailureEvidence) -> TriageLabel:
        return stub_triage(failure)


class ProseWrappingStubAIProvider:
    """A stub that mimics a REAL model's MESSY output (B5→B6, ADR-0037).

    A real model wraps generated code in lead-in prose, a ```php fence, and a
    trailing "Key decisions" table — which the clean ``StubAIProvider`` never did,
    so the prose-wrapping gap slipped the hermetic suite. This provider reproduces
    that shape so the suite proves the extractor recovers a directly-runnable
    script. It emits a PHPUnit-style Laravel feature-test CLASS (the dialect both
    PHPUnit and Pest run). ``uses_factory=True`` additionally calls
    ``Model::factory()`` to exercise the missing-factory fallback.
    """

    def __init__(self, *, uses_factory: bool = False) -> None:
        self._uses_factory = uses_factory

    def generate(self, prompt: str, context: Subgraph, budget_tokens: int) -> str:
        fingerprint = hashlib.sha256(
            f"{prompt}\x00{context.render()}".encode()
        ).hexdigest()[:12]
        setup = (
            "        \\App\\Models\\Country::factory()->create(['id' => 1]);\n"
            if self._uses_factory
            else ""
        )
        return (
            "Here is the PHPUnit feature test for this endpoint. I chose `postJson` "
            "so Laravel returns the JSON validation envelope.\n\n"
            "```php\n"
            "<?php\n\n"
            "namespace Tests\\Feature;\n\n"
            "use Tests\\TestCase;\n"
            "use Illuminate\\Foundation\\Testing\\RefreshDatabase;\n\n"
            f"class Case{fingerprint}Test extends TestCase\n"
            "{\n"
            "    use RefreshDatabase;\n\n"
            f"    public function test_case_{fingerprint}(): void\n"
            "    {\n"
            f"{setup}"
            "        $response = $this->postJson('api/users', "
            "['email' => 'a@b.test']);\n"
            "        $response->assertStatus(422);\n"
            "        $response->assertJsonValidationErrors(['name']);\n"
            "    }\n"
            "}\n"
            "```\n\n"
            "**Key decisions:**\n\n"
            "| Decision | Reason |\n"
            "|---|---|\n"
            "| `RefreshDatabase` | clean DB between tests |\n"
            "| `postJson` | sets the JSON Accept header so validation returns 422 |\n"
        )

    def triage(self, failure: FailureEvidence) -> TriageLabel:
        return stub_triage(failure)
