"""Deterministic fake AIProvider for tests (Standards §15).

Returns canned, valid output derived from the input so the test suite never
calls the real model — no cost, no network, no flakiness. Same input always
yields the same output.
"""

from __future__ import annotations

import hashlib

from .types import FailureEvidence, Subgraph, TriageLabel


class StubAIProvider:
    def generate(self, prompt: str, context: Subgraph, budget_tokens: int) -> str:
        fingerprint = hashlib.sha256(
            f"{prompt}\x00{context.render()}".encode()
        ).hexdigest()[:12]
        return (
            "// stub-generated by StubAIProvider\n"
            f"// fingerprint: {fingerprint}\n"
            f"// budget_tokens: {budget_tokens}\n"
        )

    def triage(self, failure: FailureEvidence) -> TriageLabel:
        raise NotImplementedError("triage lands in Sprint 7")
